"""Load once, run many: the T4 swap + LivePortrait expression chain.

Why this module exists. scripts/profile_chain.py runs as its own PROCESS, so
every model is freed when it exits and re-running it always pays cold start
again -- its "WARM" row is warm only because it is the second run inside a
single process. That is fine for profiling and useless for iterating, and it
is confusing besides: the same cell producing 100s and then 21s looks like a
bug rather than a warm-up.

Here the state lives in the interpreter instead. Call ``warmup()`` once (a
notebook cell, or a worker's startup) and then ``run_chain()`` costs the warm
number every time. It also matches how this would actually be served: a
process loads models at boot and handles many requests.

ORDER MATTERS. LivePortrait runs AFTER the swap. Run it before and T4
regenerates the head from the donor crop, normalising the edited expression
away -- measured directly: an opened mouth came back as an ordinary closed
smile. Anything upstream of the swap gets regenerated by it, which is the
same finding CHECKPOINT-11..14 recorded for prompt edits.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any

_STATE: dict[str, Any] = {"pipe": None, "cfg": None, "warm": False}

DEFAULTS = {
    "driving_multiplier": 0.8,
    "animation_region": "lip",
    "skip_refine": True,
    "remove_headwear": True,
    "erase_headwear": True,
    "seed": 46,
}


def _repo() -> Path:
    return Path(__file__).resolve().parents[2]


def load_models(
    *,
    seed: int = 46,
    skip_refine: bool = True,
    remove_headwear: bool = True,
    config_path: str | Path | None = None,
) -> Any:
    """Build (or return) the Krea2 pipeline. Cheap on repeat calls."""
    if _STATE["pipe"] is not None:
        return _STATE["pipe"]

    from headswap.config import load_config  # noqa: PLC0415
    from headswap.pipelines import create_pipeline  # noqa: PLC0415
    from headswap.pipelines.krea2 import (  # noqa: PLC0415
        get_shared_krea2_runtime,
    )

    cfg = load_config(
        Path(config_path) if config_path
        else _repo() / "configs" / "krea2_identity_edit.yaml"
    )
    cfg.update({"seed": int(seed), "verbose": False,
                "pre_edit_donor_expression": False})
    if skip_refine:
        # 0.25 matches simple_full_body_restore_max_face_frac, which already
        # encodes "is this a bust shot?". face_refine is a second full
        # sampling pass worth ~20s of ~40s; CHECKPOINT-12 measured it as
        # visually indistinguishable on a 42% bust shot.
        cfg["simple_full_body_refine_max_face_frac"] = 0.25
    if remove_headwear:
        # T4's base prompt only says "anything worn on the head", which was
        # not enough: a target wearing a cap kept the cap through the swap.
        # This appends an explicit remove-and-replace clause that already
        # existed in the codebase but shipped default-off and was never run
        # on GPU.
        #
        # Prompt fix, not a mask fix. CHECKPOINT-07's headwear GHOST came
        # from _head_matte_mask chopping rigid headwear out of the generation
        # mask, but this route runs raw_model (body_restore, LAB wash and
        # skin_repaint all disabled), so there is no mask and no composite
        # boundary for a ghost to appear at. CHECKPOINT-05 records the cost
        # of getting that backwards: "several rounds were wrongly spent
        # debugging masks/blending before this was found."
        #
        # Note preserve_headwear in the yaml does NOT reach this route -- it
        # only feeds _append_headwear_policy, which run_simple_full_body
        # never calls.
        cfg["simple_full_body_remove_headwear"] = True
    _STATE["cfg"] = cfg
    _STATE["pipe"] = create_pipeline(
        cfg, runtime=get_shared_krea2_runtime(init_custom_nodes=True)
    )
    return _STATE["pipe"]



def ensure_simple_lama() -> dict[str, Any]:
    """Make sure the LaMa inpainting backend for headwear erase is importable.

    Lives HERE, not in a notebook cell, and that is the whole point. Only
    setup_colab.sh installs simple-lama, and Cell 1 skips that script
    whenever ComfyUI is already present, so a reconnected runtime silently
    lacks it and erase_headwear() falls back with the hat still on. Putting
    the install in the notebook did not fix it either: Colab caches cell
    source in the browser tab, so a stale tab kept running the old cell while
    the repo code was current. Repo code is what `git pull` actually reaches.

    Installed WITH the pin repair: simple-lama-inpainting drags in pillow 9.5
    and numpy 1.26 as transitive deps, which break rembg and
    restore_background with no error at all -- they just start silently
    falling back. setup_colab.sh documents that trap; this repeats the repair
    rather than inheriting the damage.
    """
    import subprocess  # noqa: PLC0415
    import sys  # noqa: PLC0415

    try:
        import simple_lama_inpainting  # noqa: F401,PLC0415

        return {"available": True, "installed_now": False}
    except ImportError:
        pass

    print("[chain] simple-lama missing -- installing it (+ pin repair) so "
          "headwear erase can run ...", flush=True)
    pip = [sys.executable, "-m", "pip", "install", "-q"]
    subprocess.run([*pip, "simple-lama-inpainting"], check=False)
    subprocess.run([*pip, "--force-reinstall", "--no-deps", "pillow==11.3.0"],
                   check=False)
    subprocess.run([*pip, "--no-cache-dir", "--force-reinstall", "--no-deps",
                    "numpy==2.4.6"], check=False)
    try:
        import simple_lama_inpainting  # noqa: F401,PLC0415

        print("[chain] simple-lama OK", flush=True)
        return {"available": True, "installed_now": True}
    except ImportError as exc:
        print(f"[chain] WARN: simple-lama still unavailable ({exc}); "
              "headwear erase will skip and the hat will remain", flush=True)
        return {"available": False, "error": str(exc)}


def warmup(
    body_path: str | Path,
    face_path: str | Path,
    *,
    lp_dir: str | Path = "/content/LivePortrait",
    out_dir: str | Path | None = None,
    **kw: Any,
) -> dict[str, Any]:
    """Load everything AND run one throwaway pass.

    The throwaway pass is the point. Loading weights is only part of cold
    start: the first inference also pays CUDA kernel compilation and
    allocator growth, which is why LivePortrait measured 31.5s on its first
    call and 0.3s afterwards with the same models resident. Without a real
    pass here, the first ``run_chain()`` would still be slow and the timing
    would look non-deterministic.
    """
    t0 = time.perf_counter()
    if bool(kw.get("erase_headwear", DEFAULTS["erase_headwear"])):
        ensure_simple_lama()
    load_models(
        seed=int(kw.get("seed", DEFAULTS["seed"])),
        skip_refine=bool(kw.get("skip_refine", DEFAULTS["skip_refine"])),
        remove_headwear=bool(
            kw.get("remove_headwear", DEFAULTS["remove_headwear"])
        ),
    )
    out = Path(out_dir) if out_dir else (_repo() / "results" / "_warmup")
    res = run_chain(body_path, face_path, out_dir=out, lp_dir=lp_dir, **kw)
    _STATE["warm"] = True
    total = time.perf_counter() - t0
    print(f"[chain] warmup complete in {total:.1f}s -- run_chain() is now warm",
          flush=True)
    return {"warmup_s": round(total, 2), "first_pass": res}


def run_chain(
    body_path: str | Path,
    face_path: str | Path,
    *,
    out_dir: str | Path,
    lp_dir: str | Path = "/content/LivePortrait",
    driving_multiplier: float | None = None,
    animation_region: str | None = None,
    use_liveportrait: bool = True,
    erase_headwear_first: bool | None = None,
    **_ignored: Any,
) -> dict[str, Any]:
    """One request: T4 swap, then LivePortrait on its output.

    ``body_path`` supplies pose/clothing/background AND the expression to
    take; ``face_path`` supplies the identity.
    """
    from PIL import Image  # noqa: PLC0415

    pipe = load_models()
    if erase_headwear_first is None:
        erase_headwear_first = bool(DEFAULTS["erase_headwear"])
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    body_path, face_path = Path(body_path), Path(face_path)

    body_im = Image.open(body_path).convert("RGB")

    # ERASE the target's headwear BEFORE the swap, rather than asking the
    # model to remove it.
    #
    # Three prompt variants failed on GPU: the base "anything worn on the
    # head" wording, an explicit CRITICAL remove-and-replace clause
    # (chars=943), and that clause with the contradicting "keep the clothing"
    # sentence scoped below the neck (chars=958). A Nike cap and a durag both
    # survived all three. At denoise=0.85 the sampler starts from a source
    # latent that already contains a large, high-contrast object, and text
    # does not outweigh it.
    #
    # So take it out of the latent instead. erase_headwear() is LaMa
    # inpainting and already exists here for exactly this. Failures are
    # non-fatal: the swap still runs on the original body, because a missing
    # inpainting backend must degrade rather than break the request.
    erase_info: dict[str, Any] = {"applied": False}
    if erase_headwear_first:
        try:
            import numpy as _np  # noqa: PLC0415

            from headswap.headwear_erase import (  # noqa: PLC0415
                erase_headwear as _erase,
                headwear_mask as _hw_mask,
            )
            from headswap.preprocess import (  # noqa: PLC0415
                detect_best_face, pil_to_rgb_np,
            )
            from headswap.segmentation import _person_matte  # noqa: PLC0415

            _rgb = pil_to_rgb_np(body_im)
            _fb = detect_best_face(_rgb, _repo() / ".cache" / "headswap_v2")
            _matte, _mreason = _person_matte(body_im)
            if _fb is None:
                erase_info["reason"] = "no_face_detected"
            elif _matte is None:
                erase_info["reason"] = f"no_person_matte: {_mreason}"
            else:
                _mask = _hw_mask(body_im, _fb, _matte)
                _cov = float((_np.asarray(_mask) > 127).mean())
                if _cov <= 0.0005:
                    erase_info.update(reason="no headwear detected",
                                      coverage=round(_cov, 5))
                else:
                    _plate, _einfo = _erase(body_im, _mask)
                    _einfo = _einfo or {}
                    # Trust the callee's own verdict. erase_headwear falls
                    # back and returns the image UNCHANGED when its backend
                    # is missing, so assuming success here printed "headwear
                    # erased (coverage=10.098%)" immediately followed by
                    # "NOT applied: simple_lama_missing" -- two contradictory
                    # lines about the same call, because {"applied": True}
                    # was then overwritten by the spread.
                    erase_info = {**_einfo, "coverage": round(_cov, 5)}
                    erase_info.setdefault("applied", False)
                    if erase_info["applied"]:
                        body_im = _plate
                        body_im.save(out / "body_headwear_erased.png")
                        print(f"[chain] headwear ERASED (coverage={_cov:.3%})"
                              " -> body_headwear_erased.png", flush=True)
        except Exception as exc:  # noqa: BLE001
            erase_info = {"applied": False,
                          "reason": f"{type(exc).__name__}: {exc}"}
        if not erase_info.get("applied"):
            print(f"[chain] headwear erase NOT applied: "
                  f"{erase_info.get('reason')}", flush=True)

    t_swap0 = time.perf_counter()
    res = pipe.run(body_im, Image.open(face_path).convert("RGB"), out_dir=out)
    swap_s = time.perf_counter() - t_swap0
    swap_png = out / "swap_only.png"
    res.image.save(swap_png)

    final_path, lp_s, lp_used = swap_png, 0.0, False
    if use_liveportrait:
        from headswap.expression_transfer import (  # noqa: PLC0415
            run_expression_transfer,
        )
        t_lp0 = time.perf_counter()
        try:
            lp = run_expression_transfer(
                source_path=swap_png,     # identity to KEEP: T4's output
                driving_path=body_path,   # expression to TAKE: the target
                out_dir=out / "lp",
                animation_region=(animation_region
                                  or DEFAULTS["animation_region"]),
                driving_multiplier=(driving_multiplier
                                    if driving_multiplier is not None
                                    else DEFAULTS["driving_multiplier"]),
                live_portrait_dir=lp_dir,
            )
            prim = lp.get("primary")
            if prim and Path(prim).suffix.lower() != ".mp4":
                final_path, lp_used = Path(prim), True
        except Exception as exc:  # noqa: BLE001
            # Never fail the whole request because the expression step did.
            # The swap is the product; the expression is an enhancement.
            print(f"[chain] LivePortrait failed ({type(exc).__name__}: {exc}); "
                  "returning the swap unmodified", flush=True)
        lp_s = time.perf_counter() - t_lp0

    final_png = out / "final.png"
    Image.open(final_path).convert("RGB").save(final_png)
    total = swap_s + lp_s
    print(f"[chain] swap {swap_s:.1f}s + liveportrait {lp_s:.1f}s "
          f"= {total:.1f}s  (lp_applied={lp_used})", flush=True)
    return {
        "final": final_png, "swap_only": swap_png,
        "swap_s": round(swap_s, 2), "lp_s": round(lp_s, 2),
        "total_s": round(total, 2), "lp_applied": lp_used,
        "headwear_erased": erase_info,
        "was_warm": bool(_STATE["warm"]),
    }
