"""Load once, run many: the T4 swap + LivePortrait expression chain.

Why this module exists. scripts/profile_chain.py runs as its own PROCESS, so
every model is freed when it exits and re-running it always pays cold start
again -- its "WARM" row is warm only because it is the second run inside a
single process. That is fine for profiling and useless for iterating, and it
is confusing besides: the same cell producing 100s and then 21s looks like a
bug rather than a warm-up.

Here the state lives in the interpreter instead. Call ``warmup()`` once (a
notebook cell, or a worker's startup) and then ``run_chain()`` costs the warm
number every time. It also matches how this would actually be served: a
process loads models at boot and handles many requests.

ORDER MATTERS. LivePortrait runs AFTER the swap. Run it before and T4
regenerates the head from the donor crop, normalising the edited expression
away -- measured directly: an opened mouth came back as an ordinary closed
smile. Anything upstream of the swap gets regenerated by it, which is the
same finding CHECKPOINT-11..14 recorded for prompt edits.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any

_STATE: dict[str, Any] = {"pipe": None, "cfg": None, "warm": False}

DEFAULTS = {
    "driving_multiplier": 0.8,
    "animation_region": "lip",
    "skip_refine": True,
    "seed": 46,
}


def _repo() -> Path:
    return Path(__file__).resolve().parents[2]


def load_models(
    *,
    seed: int = 46,
    skip_refine: bool = True,
    config_path: str | Path | None = None,
) -> Any:
    """Build (or return) the Krea2 pipeline. Cheap on repeat calls."""
    if _STATE["pipe"] is not None:
        return _STATE["pipe"]

    from headswap.config import load_config  # noqa: PLC0415
    from headswap.pipelines import create_pipeline  # noqa: PLC0415
    from headswap.pipelines.krea2 import (  # noqa: PLC0415
        get_shared_krea2_runtime,
    )

    cfg = load_config(
        Path(config_path) if config_path
        else _repo() / "configs" / "krea2_identity_edit.yaml"
    )
    cfg.update({"seed": int(seed), "verbose": False,
                "pre_edit_donor_expression": False})
    if skip_refine:
        # 0.25 matches simple_full_body_restore_max_face_frac, which already
        # encodes "is this a bust shot?". face_refine is a second full
        # sampling pass worth ~20s of ~40s; CHECKPOINT-12 measured it as
        # visually indistinguishable on a 42% bust shot.
        cfg["simple_full_body_refine_max_face_frac"] = 0.25
    _STATE["cfg"] = cfg
    _STATE["pipe"] = create_pipeline(
        cfg, runtime=get_shared_krea2_runtime(init_custom_nodes=True)
    )
    return _STATE["pipe"]


def warmup(
    body_path: str | Path,
    face_path: str | Path,
    *,
    lp_dir: str | Path = "/content/LivePortrait",
    out_dir: str | Path | None = None,
    **kw: Any,
) -> dict[str, Any]:
    """Load everything AND run one throwaway pass.

    The throwaway pass is the point. Loading weights is only part of cold
    start: the first inference also pays CUDA kernel compilation and
    allocator growth, which is why LivePortrait measured 31.5s on its first
    call and 0.3s afterwards with the same models resident. Without a real
    pass here, the first ``run_chain()`` would still be slow and the timing
    would look non-deterministic.
    """
    t0 = time.perf_counter()
    load_models(seed=int(kw.get("seed", DEFAULTS["seed"])),
                skip_refine=bool(kw.get("skip_refine", DEFAULTS["skip_refine"])))
    out = Path(out_dir) if out_dir else (_repo() / "results" / "_warmup")
    res = run_chain(body_path, face_path, out_dir=out, lp_dir=lp_dir, **kw)
    _STATE["warm"] = True
    total = time.perf_counter() - t0
    print(f"[chain] warmup complete in {total:.1f}s -- run_chain() is now warm",
          flush=True)
    return {"warmup_s": round(total, 2), "first_pass": res}


def run_chain(
    body_path: str | Path,
    face_path: str | Path,
    *,
    out_dir: str | Path,
    lp_dir: str | Path = "/content/LivePortrait",
    driving_multiplier: float | None = None,
    animation_region: str | None = None,
    use_liveportrait: bool = True,
    **_ignored: Any,
) -> dict[str, Any]:
    """One request: T4 swap, then LivePortrait on its output.

    ``body_path`` supplies pose/clothing/background AND the expression to
    take; ``face_path`` supplies the identity.
    """
    from PIL import Image  # noqa: PLC0415

    pipe = load_models()
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    body_path, face_path = Path(body_path), Path(face_path)

    t_swap0 = time.perf_counter()
    res = pipe.run(Image.open(body_path).convert("RGB"),
                   Image.open(face_path).convert("RGB"), out_dir=out)
    swap_s = time.perf_counter() - t_swap0
    swap_png = out / "swap_only.png"
    res.image.save(swap_png)

    final_path, lp_s, lp_used = swap_png, 0.0, False
    if use_liveportrait:
        from headswap.expression_transfer import (  # noqa: PLC0415
            run_expression_transfer,
        )
        t_lp0 = time.perf_counter()
        try:
            lp = run_expression_transfer(
                source_path=swap_png,     # identity to KEEP: T4's output
                driving_path=body_path,   # expression to TAKE: the target
                out_dir=out / "lp",
                animation_region=(animation_region
                                  or DEFAULTS["animation_region"]),
                driving_multiplier=(driving_multiplier
                                    if driving_multiplier is not None
                                    else DEFAULTS["driving_multiplier"]),
                live_portrait_dir=lp_dir,
            )
            prim = lp.get("primary")
            if prim and Path(prim).suffix.lower() != ".mp4":
                final_path, lp_used = Path(prim), True
        except Exception as exc:  # noqa: BLE001
            # Never fail the whole request because the expression step did.
            # The swap is the product; the expression is an enhancement.
            print(f"[chain] LivePortrait failed ({type(exc).__name__}: {exc}); "
                  "returning the swap unmodified", flush=True)
        lp_s = time.perf_counter() - t_lp0

    final_png = out / "final.png"
    Image.open(final_path).convert("RGB").save(final_png)
    total = swap_s + lp_s
    print(f"[chain] swap {swap_s:.1f}s + liveportrait {lp_s:.1f}s "
          f"= {total:.1f}s  (lp_applied={lp_used})", flush=True)
    return {
        "final": final_png, "swap_only": swap_png,
        "swap_s": round(swap_s, 2), "lp_s": round(lp_s, 2),
        "total_s": round(total, 2), "lp_applied": lp_used,
        "was_warm": bool(_STATE["warm"]),
    }
